//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixiShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoresAddress
    {
        public int ID { get; set; }
        public int ShopID { get; set; }
        public string GoogleMapPath { get; set; }
        public string Address { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
